// <auto-generated />
using System;
using Kho.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kho.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KhoDbContext))]
    [Migration("20260920145840_KhoiTao")]
    partial class KhoiTao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Kho.Domain.SanPhams.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("DonGia")
                        .HasColumnType("REAL");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("MucCanhBao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nhom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("TonKho")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Ma")
                        .IsUnique();

                    b.ToTable("san_pham", null, t =>
                        {
                            t.HasCheckConstraint("ck_gia_khong_am", "DonGia >= 0");

                            t.HasCheckConstraint("ck_ton_khong_am", "TonKho >= 0");
                        });
                });

            modelBuilder.Entity("Kho.Infrastructure.Persistence.IdempotencyRecord", b =>
                {
                    b.Property<string>("Khoa")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DauVan")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("LoaiNoiDung")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaTrangThai")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NoiDung")
                        .HasColumnType("TEXT");

                    b.Property<long>("TaoLucMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Khoa");

                    b.ToTable("idempotency", (string)null);
                });

            modelBuilder.Entity("Kho.Infrastructure.Persistence.NhatKyKiemToan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DoiTuong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long>("Luc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nguoi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sau")
                        .HasColumnType("TEXT");

                    b.Property<string>("Truoc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Luc");

                    b.ToTable("nhat_ky_kiem_toan", (string)null);
                });

            modelBuilder.Entity("Kho.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Loai")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LoiCuoi")
                        .HasColumnType("TEXT");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SoLanThu")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TaoLuc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("XuLyLuc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("XuLyLuc", "TaoLuc");

                    b.ToTable("outbox", (string)null);
                });

            modelBuilder.Entity("Kho.Infrastructure.Persistence.SanPhamDoc", b =>
                {
                    b.Property<double>("DonGia")
                        .HasColumnType("REAL");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MucCanhBao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nhom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TonKho")
                        .HasColumnType("INTEGER");

                    b.ToTable("SanPhamDocs");

                    b.ToSqlQuery("SELECT Id, Ma, Ten, Nhom, DonGia, TonKho, MucCanhBao FROM san_pham");
                });
#pragma warning restore 612, 618
        }
    }
}
