// <auto-generated />
using CuaHang.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CuaHang.Migrations
{
    [DbContext(typeof(CuaHangDbContext))]
    [Migration("20260920071842_KhoiTao")]
    partial class KhoiTao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("CuaHang.Models.Nhom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ten")
                        .IsUnique();

                    b.ToTable("nhom", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ten = "Phu kien"
                        },
                        new
                        {
                            Id = 2,
                            Ten = "Thiet bi"
                        });
                });

            modelBuilder.Entity("CuaHang.Models.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Gia")
                        .HasColumnType("REAL");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("NhomId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ton")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Ma")
                        .IsUnique();

                    b.HasIndex("NhomId");

                    b.ToTable("san_pham", null, t =>
                        {
                            t.HasCheckConstraint("ck_san_pham_gia", "Gia >= 0");
                        });
                });

            modelBuilder.Entity("CuaHang.Models.SanPham", b =>
                {
                    b.HasOne("CuaHang.Models.Nhom", "Nhom")
                        .WithMany("SanPhams")
                        .HasForeignKey("NhomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Nhom");
                });

            modelBuilder.Entity("CuaHang.Models.Nhom", b =>
                {
                    b.Navigation("SanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
